parameters:
#    tox_parser.example.class: Tox\ParserBundle\Example

services:
#    tox_parser.example:
#        class: %tox_parser.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
