parameters:
#    tox_parser.example.class: Tox\ParserBundle\Example

services:
    var_dump.twig.extension:
        class: Tox\ParserBundle\Twig\Extension\VarDumpExtension
        tags:
            -  { name: twig.extension }
#    tox_parser.example:
#        class: %tox_parser.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
