ALTER TABLE Account CHANGE username username VARCHAR(255) NOT NULL;
ALTER TABLE FtpAccount ADD shell_version VARCHAR(255) DEFAULT NULL;
ALTER TABLE HttpAccount CHANGE login_field login_field VARCHAR(255) DEFAULT NULL, CHANGE password_field password_field VARCHAR(255) DEFAULT NULL, CHANGE url url VARCHAR(255) DEFAULT NULL;
ALTER TABLE Satellite ADD title VARCHAR(255) DEFAULT NULL, ADD keys LONGTEXT DEFAULT NULL, ADD description LONGTEXT DEFAULT NULL, ADD about LONGTEXT DEFAULT NULL, ADD key VARCHAR(255) DEFAULT NULL
