parameters:
#    tox_satellite.example.class: Tox\SatelliteBundle\Example

services:
#    tox_satellite.example:
#        class: %tox_satellite.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
