Tox\PlaceBundle\Entity\Host:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    url:
      type: string
      nullable: false
    ns_servers:
      type: text
      nullable: true
  oneToMany:
    Accounts:
      targetEntity: Tox\PlaceBundle\Entity\HostAccount
      mappedBy: Host
