Tox\PlaceBundle\Entity\HttpAccount:
  type: entity
  inheritanceType: JOINED
  fields:
    login_field:
      type: string
      length: 255
      nullable: true
    password_field:
      type: string
      length: 255
      nullable: true
    url:
      type: string
      length: 255
      nullable: true
  discriminatorColumn:
    name: descriminator
    length: 255
    type: string
  discriminatorMap:
    HostAccount: Tox\PlaceBundle\Entity\HostAccount
    SourceAccount: Tox\ParserBundle\Entity\SourceAccount