Tox\PlaceBundle\Entity\Register:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    url:
      type: string
      unique: true
      nullable: false
  oneToMany:
    Accounts:
      targetEntity: Tox\PlaceBundle\Entity\RegisterAccount
      mappedBy: Register
