Tox\PlaceBundle\Entity\SearchEngine:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator: { strategy: AUTO }
    name:
      type: string
      nullable: false
  oneToMany:
    Indexes:
      targetEntity: Tox\PlaceBundle\Entity\Indexed
      mappedBy: SearchEngine
