Tox\ParserBundle\Entity\Bot:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator: { strategy: AUTO }
    vkid:
      type: integer
      unique: true
      nullable: false
    first_name:
      type: string
      nullable: false
    last_name:
      type: string
      nullable: false
    email:
      type: string
      nullable: true
    phone:
      type: string
      nullable: true
  oneToMany:
    Domens:
      targetEntity: Tox\PlaceBundle\Entity\Domen
      mappedBy: Bot
