Tox\ParserBundle\Entity\Content:
  type: entity
  fields:
    data:
      type: text
      length: 10000
      nullable: false
  oneToMany:
    Meta:
      targetEntity: Tox\ParserBundle\Entity\MetaData
      mappedBy: Content
