Tox\ParserBundle\Entity\Content:
  type: entity
  fields: null
  oneToMany:
    Posts:
      targetEntity: Tox\SatelliteBundle\Entity\Post
      mappedBy: Content
    Meta:
      targetEntity: Tox\ParserBundle\Entity\MetaData
      mappedBy: Content
