Tox\ParserBundle\Entity\PatternType:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      nullable: false
  oneToMany:
    MetaData:
      targetEntity: Tox\ParserBundle\Entity\MetaData
      mappedBy: PatternType
    Rules:
      targetEntity: Tox\ParserBundle\Entity\Rule
      mappedBy: Type
  manyToOne:
    Type:
      targetEntity: Tox\ParserBundle\Entity\SourceType
      inversedBy: Patterns
      joinColumns:
        source_type_id:
          referencedColumnName: id
