Tox\ParserBundle\Entity\Schedule:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    timeout:
      type: integer
      nullable: false
  oneToMany:
    Source:
      targetEntity: Tox\ParserBundle\Entity\Source
      mappedBy: Schedule
