Tox\ParserBundle\Entity\Source:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    url:
      type: string
      unique: true
      nullable: false
    parsed_at:
      type: datetime
      nullable: true
  oneToOne:
    Account:
      targetEntity: Tox\ParserBundle\Entity\SourceAccount
      mappedBy: Source
  oneToMany:
    Results:
      targetEntity: Tox\ParserBundle\Entity\RawResult
      mappedBy: Source
    Rules:
      targetEntity: Tox\ParserBundle\Entity\Rule
      mappedBy: Source
      orphanRemoval: true
    UsedProxy:
      targetEntity: Tox\ParserBundle\Entity\UsedProxy
      mappedBy: Source
  manyToOne:
    Theme:
      targetEntity: Tox\SatelliteBundle\Entity\Theme
      inversedBy: Sources
      joinColumns:
        theme_id:
          referencedColumnName: id
    Schedule:
      targetEntity: Tox\ParserBundle\Entity\Schedule
      inversedBy: Source
      joinColumns:
        schedule_id:
          referencedColumnName: id
    Type:
      targetEntity: Tox\ParserBundle\Entity\SourceType
      inversedBy: Sources
      joinColumns:
        source_type_id:
          referencedColumnName: id
