Tox\ParserBundle\Entity\SourceType:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      nullable: false
  oneToMany:
    Sources:
      targetEntity: Tox\ParserBundle\Entity\Source
      mappedBy: Type
    Patterns:
      targetEntity: Tox\ParserBundle\Entity\PatternType
      mappedBy: Type
