Tox\ParserBundle\Entity\Source:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator: { strategy: AUTO }
    name:
      type: string
      nullable: true
    url:
      type: string
      nullable: false
  oneToMany:
    RawPages:
      targetEntity: Tox\ParserBundle\Entity\RawText
      mappedBy: Source
  manyToOne:
    Theme:
      targetEntity: Tox\SatelliteBundle\Entity\Theme
      inversedBy: Sources
      joinColumns: { theme_id: { referencedColumnName: id } }
