Tox\SatelliteBundle\Entity\DomenHistory:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator: { strategy: AUTO }
    changet_at:
      type: date
      nullable: false
  manyToOne:
    Satellite:
      targetEntity: Tox\SatelliteBundle\Entity\Satellite
      inversedBy: History
      joinColumns: { satellite_id: { referencedColumnName: id } }
    Domen:
      targetEntity: Tox\PlaceBundle\Entity\Domen
      inversedBy: History
      joinColumns: { domen_id: { referencedColumnName: id } }
