Tox\SatelliteBundle\Entity\Image:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      nullable: false
  manyToOne:
    Post:
      targetEntity: Tox\SatelliteBundle\Entity\Post
      inversedBy: Images
      joinColumns:
        post_id:
          referencedColumnName: id
