Tox\SatelliteBundle\Entity\Theme:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator: { strategy: AUTO }
    name:
      type: string
      nullable: false
  oneToMany:
    Satellites:
      targetEntity: Tox\SatelliteBundle\Entity\Satellite
      mappedBy: Theme
    RawPages:
      targetEntity: Tox\ParserBundle\Entity\RawText
      mappedBy: Theme
    Sources:
      targetEntity: Tox\ParserBundle\Entity\Source
      mappedBy: Theme
